name: Master

on:
  push:
    branches: [development]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Create Virtual env
#       sudo apt-get update
#       sudo apt-get -y install python3-venv
        run: |
          mkdir actionenv
          cd actionenv
          /usr/bin/python3.8 -m venv venv
          source venv/bin/activate
          cd ..
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip freeze
      - name: Django Commands
        run: |
          python3 manage.py makemigrations
          python3 manage.py migrate
  test:
    runs-on: self-hosted
    needs: [build]
    steps:
      - name: Run Tests
        run: |
          source actionenv/venv/bin/activate
          python3 manage.py test
  
  scan:
    runs-on: self-hosted
    needs: [build]
    steps:
      - name: OWASP ZAP Full Scan
        # You may pin to the exact commit or the version.
        # uses: zaproxy/action-full-scan@6eade0f93b10fad8cfb4e63b979703a2cbd0cc98
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          # GitHub Token to create issues in the repository
#           token: # optional, default is ${{ github.token }}
          # Target URL
          target: 'https://arjunmadavoor.com'
#           # Relative path of the ZAP configuration file
#           rules_file_name: # optional
#           # The Docker file to be executed
#           docker_name: # default is owasp/zap2docker-stable
#           # Additional command line options
#           cmd_options: # optional
#           # The title for the GitHub issue to be created
#           issue_title: # optional, default is ZAP Full Scan Report
#           # The action status will be set to fail if ZAP identifies any alerts during the full scan
#           fail_action: # optional
#           # Whether Github issues should be created or not
#           allow_issue_writing: # optional, default is true
  
  
  deploy:
    runs-on: self-hosted
    needs: [build, test]
    steps:
      - name: Add remote heroku repo & Deploy!
        #       run: |
        #       git remote add heroku https://heroku:${{secrets.HEROKU_SECRET_KEY}}@git.heroku.com/djangoaction.git
        run: |
          git commit -m "update"
          git push heroku master -f
#   Setup-Notification:
#     runs-on: self-hosted
#     needs: [build, test, deploy]
#     steps:
#       - name: Google Chat Notification
#         uses: Co-qn/google-chat-notification@releases/v1
#         with:
#           name: Build
#           url: ${{ secrets.GOOGLE_CHAT }}
#           status: ${{ job.status }}
