name: Django CI CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  build:
    runs-on: self-hosted
    strategy:
  #   fail-fast: false
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Create Virtual env
        run: |
          sudo apt-get update
          sudo apt-get -y install python3-venv
          mkdir actionenv
          cd actionenv
          /usr/bin/python3.8 -m venv venv
          source venv/bin/activate
          cd ..
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip freeze

      - name: Django Commands
        run: |
          python3 manage.py makemigrations
          python3 manage.py migrate

  test:
    runs-on: self-hosted
    needs: [build]
    steps:
      - name: Run Tests
        run: |
          source actionenv/venv/bin/activate
          python3 manage.py test

  deploy:
    runs-on: self-hosted
    needs: [build, test]
    steps:
      - name: Add remote heroku repo & Deploy!
        #       run: |
        #       git remote add heroku https://heroku:${{secrets.HEROKU_SECRET_KEY}}@git.heroku.com/djangoaction.git
        #       if: github.ref == 'ref/heads/master' && job.status == 'success'
        run: git push heroku master -f

  Setup-Notification:
    runs-on: self-hosted
    needs: [build, test, deploy]
    steps:
      - name: Google Chat Notification
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: Build
          url: ${{ secrets.GOOGLE_CHAT }}
          status: ${{ job.status }}
