name: Issue Creation Tracker
on: push
    
jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Google Chat Notification
      run: |
          curl --location --request POST '${{ secrets.GOOGLE_CHAT }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "cards": [
                  {
                      "header": {
                          "title": "Build Status"
                      }
                  }
              ]
